INSERT INTO CATEGORIES (name) VALUES ('Acessórios para Veículos');
INSERT INTO CATEGORIES (name) VALUES ('Aces. de Carros e Caminhonetes');
INSERT INTO CATEGORIES (name) VALUES ('Aces. de Motos e Quadriciclos');
INSERT INTO CATEGORIES (name) VALUES ('Aces. e Peças para Caminhões');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios e Peças Náuticos');
INSERT INTO CATEGORIES (name) VALUES ('Ferramentas');
INSERT INTO CATEGORIES (name) VALUES ('GNV');
INSERT INTO CATEGORIES (name) VALUES ('Limpeza Automotiva');
INSERT INTO CATEGORIES (name) VALUES ('Navegadores GPS');
INSERT INTO CATEGORIES (name) VALUES ('Peças de Carros e Caminhonetes');
INSERT INTO CATEGORIES (name) VALUES ('Peças de Maquinaria Pesada');
INSERT INTO CATEGORIES (name) VALUES ('Peças de Motos e Quadriciclos');
INSERT INTO CATEGORIES (name) VALUES ('Performance');
INSERT INTO CATEGORIES (name) VALUES ('Pneus');
INSERT INTO CATEGORIES (name) VALUES ('Rodas');
INSERT INTO CATEGORIES (name) VALUES ('Segurança Veicular');
INSERT INTO CATEGORIES (name) VALUES ('Serviços Programados');
INSERT INTO CATEGORIES (name) VALUES ('Som Automotivo');
INSERT INTO CATEGORIES (name) VALUES ('Tuning');
INSERT INTO CATEGORIES (name) VALUES ('Agro');
INSERT INTO CATEGORIES (name) VALUES ('Alimentação e Suplementos');
INSERT INTO CATEGORIES (name) VALUES ('Animais');
INSERT INTO CATEGORIES (name) VALUES ('Geradores de Energia');
INSERT INTO CATEGORIES (name) VALUES ('Insumos Agrícolas');
INSERT INTO CATEGORIES (name) VALUES ('Insumos Agro-gadeiros');
INSERT INTO CATEGORIES (name) VALUES ('Máquinas e Ferramentas');
INSERT INTO CATEGORIES (name) VALUES ('Peças de Maquinaria Pesada');
INSERT INTO CATEGORIES (name) VALUES ('Alimentos e Bebidas');
INSERT INTO CATEGORIES (name) VALUES ('Bebidas');
INSERT INTO CATEGORIES (name) VALUES ('Comestíveis');
INSERT INTO CATEGORIES (name) VALUES ('Comida Preparada e Catering');
INSERT INTO CATEGORIES (name) VALUES ('Frescos');
INSERT INTO CATEGORIES (name) VALUES ('Animais');
INSERT INTO CATEGORIES (name) VALUES ('Anfíbios e Répteis');
INSERT INTO CATEGORIES (name) VALUES ('Aves e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Cachorros');
INSERT INTO CATEGORIES (name) VALUES ('Cavalos');
INSERT INTO CATEGORIES (name) VALUES ('Coelhos');
INSERT INTO CATEGORIES (name) VALUES ('Gatos');
INSERT INTO CATEGORIES (name) VALUES ('Insetos');
INSERT INTO CATEGORIES (name) VALUES ('Peixes');
INSERT INTO CATEGORIES (name) VALUES ('Roedores');
INSERT INTO CATEGORIES (name) VALUES ('Antiguidades e Coleções');
INSERT INTO CATEGORIES (name) VALUES ('Antiguidades');
INSERT INTO CATEGORIES (name) VALUES ('Cédulas e Moedas');
INSERT INTO CATEGORIES (name) VALUES ('Colecionáveis de Esportes');
INSERT INTO CATEGORIES (name) VALUES ('Esculturas');
INSERT INTO CATEGORIES (name) VALUES ('Filatelia');
INSERT INTO CATEGORIES (name) VALUES ('Militaria e Afins');
INSERT INTO CATEGORIES (name) VALUES ('Pôsteres');
INSERT INTO CATEGORIES (name) VALUES ('Outras Antiguidades');
INSERT INTO CATEGORIES (name) VALUES ('Arte, Papelaria e Armarinho');
INSERT INTO CATEGORIES (name) VALUES ('Arte');
INSERT INTO CATEGORIES (name) VALUES ('Artigos de Armarinho');
INSERT INTO CATEGORIES (name) VALUES ('Espelhos de Mosaico');
INSERT INTO CATEGORIES (name) VALUES ('Formas para Sabonetes');
INSERT INTO CATEGORIES (name) VALUES ('Insumos para Fazer Velas');
INSERT INTO CATEGORIES (name) VALUES ('Materiais Escolares');
INSERT INTO CATEGORIES (name) VALUES ('Peças para Chaveiros');
INSERT INTO CATEGORIES (name) VALUES ('Bebês');
INSERT INTO CATEGORIES (name) VALUES ('Alimentos para Bebês');
INSERT INTO CATEGORIES (name) VALUES ('Amamentação para Bebês');
INSERT INTO CATEGORIES (name) VALUES ('Andadores e Mini Veículos');
INSERT INTO CATEGORIES (name) VALUES ('Artigos de Bebê para Banho');
INSERT INTO CATEGORIES (name) VALUES ('Artigos de Maternidade');
INSERT INTO CATEGORIES (name) VALUES ('Brinquedos para Bebês');
INSERT INTO CATEGORIES (name) VALUES ('Cercadinho');
INSERT INTO CATEGORIES (name) VALUES ('Chupetas e Mordedores');
INSERT INTO CATEGORIES (name) VALUES ('Higiene e Cuidados com o Bebê');
INSERT INTO CATEGORIES (name) VALUES ('Passeio Do Bebê');
INSERT INTO CATEGORIES (name) VALUES ('Quarto do Bebê');
INSERT INTO CATEGORIES (name) VALUES ('Roupas de Bebê');
INSERT INTO CATEGORIES (name) VALUES ('Saúde do Bebê');
INSERT INTO CATEGORIES (name) VALUES ('Segurança para Bebê');
INSERT INTO CATEGORIES (name) VALUES ('Beleza e Cuidado Pessoal');
INSERT INTO CATEGORIES (name) VALUES ('Artigos para Cabeleireiros');
INSERT INTO CATEGORIES (name) VALUES ('Barbearia');
INSERT INTO CATEGORIES (name) VALUES ('Cuidados com a Pele');
INSERT INTO CATEGORIES (name) VALUES ('Cuidados com o Cabelo');
INSERT INTO CATEGORIES (name) VALUES ('Depilação');
INSERT INTO CATEGORIES (name) VALUES ('Eletrodomésticos de Beleza');
INSERT INTO CATEGORIES (name) VALUES ('Farmácia');
INSERT INTO CATEGORIES (name) VALUES ('Higiene Pessoal');
INSERT INTO CATEGORIES (name) VALUES ('Manicure e Pedicure');
INSERT INTO CATEGORIES (name) VALUES ('Maquiagem');
INSERT INTO CATEGORIES (name) VALUES ('Perfumes');
INSERT INTO CATEGORIES (name) VALUES ('Splash Corporal');
INSERT INTO CATEGORIES (name) VALUES ('Tratamentos de Beleza');
INSERT INTO CATEGORIES (name) VALUES ('Brinquedos e Hobbies');
INSERT INTO CATEGORIES (name) VALUES ('Álbuns e Figurinhas');
INSERT INTO CATEGORIES (name) VALUES ('Anti-stress e Engenho');
INSERT INTO CATEGORIES (name) VALUES ('Ar Livre e Playground');
INSERT INTO CATEGORIES (name) VALUES ('Blocos e Construção');
INSERT INTO CATEGORIES (name) VALUES ('Bonecos e Bonecas');
INSERT INTO CATEGORIES (name) VALUES ('Brinquedos de Água e Praia');
INSERT INTO CATEGORIES (name) VALUES ('Brinquedos de Pegadinhas');
INSERT INTO CATEGORIES (name) VALUES ('Brinquedos de Profissões');
INSERT INTO CATEGORIES (name) VALUES ('Brinquedos para Bebês');
INSERT INTO CATEGORIES (name) VALUES ('Casinhas e Barracas');
INSERT INTO CATEGORIES (name) VALUES ('Desenho, Pintura e Artesanatos');
INSERT INTO CATEGORIES (name) VALUES ('Fantoches e Marionetas');
INSERT INTO CATEGORIES (name) VALUES ('Hobbies');
INSERT INTO CATEGORIES (name) VALUES ('Instrumentos Musicais');
INSERT INTO CATEGORIES (name) VALUES ('Jogos de Salão');
INSERT INTO CATEGORIES (name) VALUES ('Jogos de Tabuleiro e Cartas');
INSERT INTO CATEGORIES (name) VALUES ('Jogos Eletrônicos');
INSERT INTO CATEGORIES (name) VALUES ('Lançadores de Brinquedo');
INSERT INTO CATEGORIES (name) VALUES ('Mesas e Cadeiras');
INSERT INTO CATEGORIES (name) VALUES ('Mini Veículos e Bicicletas');
INSERT INTO CATEGORIES (name) VALUES ('Patins e Patinetes');
INSERT INTO CATEGORIES (name) VALUES ('Pelúcias');
INSERT INTO CATEGORIES (name) VALUES ('Piscinas e Infláveis');
INSERT INTO CATEGORIES (name) VALUES ('Upa Upa');
INSERT INTO CATEGORIES (name) VALUES ('Veículos de Brinquedo');
INSERT INTO CATEGORIES (name) VALUES ('Calçados, Roupas e Bolsas');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios da Moda');
INSERT INTO CATEGORIES (name) VALUES ('Bagagem e Bolsas');
INSERT INTO CATEGORIES (name) VALUES ('Bermudas e Shorts');
INSERT INTO CATEGORIES (name) VALUES ('Blusas');
INSERT INTO CATEGORIES (name) VALUES ('Calças');
INSERT INTO CATEGORIES (name) VALUES ('Camisas');
INSERT INTO CATEGORIES (name) VALUES ('Camisetas');
INSERT INTO CATEGORIES (name) VALUES ('Camisolas e moletons');
INSERT INTO CATEGORIES (name) VALUES ('Casacos');
INSERT INTO CATEGORIES (name) VALUES ('Leggings');
INSERT INTO CATEGORIES (name) VALUES ('Lotes de Roupa');
INSERT INTO CATEGORIES (name) VALUES ('Macacão');
INSERT INTO CATEGORIES (name) VALUES ('Moda Fitness');
INSERT INTO CATEGORIES (name) VALUES ('Moda Íntima e Lingerie');
INSERT INTO CATEGORIES (name) VALUES ('Moda Praia');
INSERT INTO CATEGORIES (name) VALUES ('Roupa de Dança e Patín');
INSERT INTO CATEGORIES (name) VALUES ('Roupas para Bebês');
INSERT INTO CATEGORIES (name) VALUES ('Saias');
INSERT INTO CATEGORIES (name) VALUES ('Sapatos');
INSERT INTO CATEGORIES (name) VALUES ('Suéteres, Cardigans e Coletes');
INSERT INTO CATEGORIES (name) VALUES ('Ternos');
INSERT INTO CATEGORIES (name) VALUES ('Uniformes');
INSERT INTO CATEGORIES (name) VALUES ('Vestidos');
INSERT INTO CATEGORIES (name) VALUES ('Câmeras e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios para Câmeras');
INSERT INTO CATEGORIES (name) VALUES ('Álbuns e Porta-retratos');
INSERT INTO CATEGORIES (name) VALUES ('Cabos');
INSERT INTO CATEGORIES (name) VALUES ('Câmeras');
INSERT INTO CATEGORIES (name) VALUES ('Drones e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento de Revelação');
INSERT INTO CATEGORIES (name) VALUES ('Filmadoras');
INSERT INTO CATEGORIES (name) VALUES ('Instrumentos Ópticos');
INSERT INTO CATEGORIES (name) VALUES ('Lentes e Filtros');
INSERT INTO CATEGORIES (name) VALUES ('Peças para Câmeras');
INSERT INTO CATEGORIES (name) VALUES ('Carros, Motos e Outros');
INSERT INTO CATEGORIES (name) VALUES ('Caminhões');
INSERT INTO CATEGORIES (name) VALUES ('Carros Antigos');
INSERT INTO CATEGORIES (name) VALUES ('Carros e Caminhonetes');
INSERT INTO CATEGORIES (name) VALUES ('Consórcios');
INSERT INTO CATEGORIES (name) VALUES ('Motorhomes');
INSERT INTO CATEGORIES (name) VALUES ('Motos');
INSERT INTO CATEGORIES (name) VALUES ('Náutica');
INSERT INTO CATEGORIES (name) VALUES ('Ônibus');
INSERT INTO CATEGORIES (name) VALUES ('Veículos Pesados');
INSERT INTO CATEGORIES (name) VALUES ('Outros Veículos');
INSERT INTO CATEGORIES (name) VALUES ('Casa, Móveis e Decoração');
INSERT INTO CATEGORIES (name) VALUES ('Banheiros');
INSERT INTO CATEGORIES (name) VALUES ('Colchões e Camas Box');
INSERT INTO CATEGORIES (name) VALUES ('Cortinas e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Cuidado da Casa e Lavanderia');
INSERT INTO CATEGORIES (name) VALUES ('Enfeites e Decoração da Casa');
INSERT INTO CATEGORIES (name) VALUES ('Iluminação Residencial');
INSERT INTO CATEGORIES (name) VALUES ('Jardins e Exteriores');
INSERT INTO CATEGORIES (name) VALUES ('Móveis para Casa');
INSERT INTO CATEGORIES (name) VALUES ('Organização para Casa');
INSERT INTO CATEGORIES (name) VALUES ('Segurança para Casa');
INSERT INTO CATEGORIES (name) VALUES ('Têxteis de Casa e Decoração');
INSERT INTO CATEGORIES (name) VALUES ('Utilidades Domésticas');
INSERT INTO CATEGORIES (name) VALUES ('Celulares e Telefones');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios para Celulares');
INSERT INTO CATEGORIES (name) VALUES ('Celulares e Smartphones');
INSERT INTO CATEGORIES (name) VALUES ('Óculos de Realidade Virtual');
INSERT INTO CATEGORIES (name) VALUES ('Peças para Celular');
INSERT INTO CATEGORIES (name) VALUES ('Smartwatches e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Tarifadores e Cabines');
INSERT INTO CATEGORIES (name) VALUES ('Telefonia Fixa e Sem Fio');
INSERT INTO CATEGORIES (name) VALUES ('VoIP');
INSERT INTO CATEGORIES (name) VALUES ('Walkie Talkies');
INSERT INTO CATEGORIES (name) VALUES ('Eletrodomésticos');
INSERT INTO CATEGORIES (name) VALUES ('Ar e Ventilação');
INSERT INTO CATEGORIES (name) VALUES ('Bebedouros e Purificadores');
INSERT INTO CATEGORIES (name) VALUES ('Cuidado Pessoal');
INSERT INTO CATEGORIES (name) VALUES ('Forno e Fogões');
INSERT INTO CATEGORIES (name) VALUES ('Geladeiras e Freezers');
INSERT INTO CATEGORIES (name) VALUES ('Lavadores');
INSERT INTO CATEGORIES (name) VALUES ('Peças e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Pequenos Eletrodomésticos');
INSERT INTO CATEGORIES (name) VALUES ('Eletrônicos, Áudio e Vídeo');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios para Áudio e Vídeo');
INSERT INTO CATEGORIES (name) VALUES ('Aparelhos DVD e Bluray');
INSERT INTO CATEGORIES (name) VALUES ('Áudio');
INSERT INTO CATEGORIES (name) VALUES ('Bolsas e Estojos');
INSERT INTO CATEGORIES (name) VALUES ('Cabos');
INSERT INTO CATEGORIES (name) VALUES ('Controles Remotos');
INSERT INTO CATEGORIES (name) VALUES ('Drones e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Media Streaming');
INSERT INTO CATEGORIES (name) VALUES ('Peças e Componentes Elétricos');
INSERT INTO CATEGORIES (name) VALUES ('Peças para TV');
INSERT INTO CATEGORIES (name) VALUES ('Pilhas e Carregadores');
INSERT INTO CATEGORIES (name) VALUES ('Projetores e Telas');
INSERT INTO CATEGORIES (name) VALUES ('TV');
INSERT INTO CATEGORIES (name) VALUES ('TV a Cabo');
INSERT INTO CATEGORIES (name) VALUES ('Outros Eletrônicos');
INSERT INTO CATEGORIES (name) VALUES ('Esportes e Fitness');
INSERT INTO CATEGORIES (name) VALUES ('Artes Marciais e Boxe');
INSERT INTO CATEGORIES (name) VALUES ('Badminton');
INSERT INTO CATEGORIES (name) VALUES ('Baseball');
INSERT INTO CATEGORIES (name) VALUES ('Basquete');
INSERT INTO CATEGORIES (name) VALUES ('Camping, Caça e Pesca');
INSERT INTO CATEGORIES (name) VALUES ('Canoas, Caiaques e Infláveis');
INSERT INTO CATEGORIES (name) VALUES ('Ciclismo');
INSERT INTO CATEGORIES (name) VALUES ('Equitação');
INSERT INTO CATEGORIES (name) VALUES ('Esgrima');
INSERT INTO CATEGORIES (name) VALUES ('Esqui e Snowboard');
INSERT INTO CATEGORIES (name) VALUES ('Fitness e Musculação');
INSERT INTO CATEGORIES (name) VALUES ('Futebol');
INSERT INTO CATEGORIES (name) VALUES ('Futebol Americano');
INSERT INTO CATEGORIES (name) VALUES ('Golfe');
INSERT INTO CATEGORIES (name) VALUES ('Handebol');
INSERT INTO CATEGORIES (name) VALUES ('Hockey');
INSERT INTO CATEGORIES (name) VALUES ('Jogos de Salão');
INSERT INTO CATEGORIES (name) VALUES ('Kitesurf');
INSERT INTO CATEGORIES (name) VALUES ('Mergulho');
INSERT INTO CATEGORIES (name) VALUES ('Moda Fitness');
INSERT INTO CATEGORIES (name) VALUES ('Monitores e Relógios');
INSERT INTO CATEGORIES (name) VALUES ('Natação');
INSERT INTO CATEGORIES (name) VALUES ('Paintball');
INSERT INTO CATEGORIES (name) VALUES ('Parapente');
INSERT INTO CATEGORIES (name) VALUES ('Patín, Ginástica e Dança');
INSERT INTO CATEGORIES (name) VALUES ('Patinetes e Scooters');
INSERT INTO CATEGORIES (name) VALUES ('Pilates e Yoga');
INSERT INTO CATEGORIES (name) VALUES ('Rapel, Montanhismo e Escalada');
INSERT INTO CATEGORIES (name) VALUES ('Rugby');
INSERT INTO CATEGORIES (name) VALUES ('Skateboard e Sandboard');
INSERT INTO CATEGORIES (name) VALUES ('Slackline');
INSERT INTO CATEGORIES (name) VALUES ('Suplementos e Shakers');
INSERT INTO CATEGORIES (name) VALUES ('Surf e Bodyboard');
INSERT INTO CATEGORIES (name) VALUES ('Tênis');
INSERT INTO CATEGORIES (name) VALUES ('Tênis e Squash');
INSERT INTO CATEGORIES (name) VALUES ('Tiro Esportivo');
INSERT INTO CATEGORIES (name) VALUES ('Vôlei');
INSERT INTO CATEGORIES (name) VALUES ('Wakeboard e Esquí Acuático');
INSERT INTO CATEGORIES (name) VALUES ('Windsurfe');
INSERT INTO CATEGORIES (name) VALUES ('Ferramentas e Construção');
INSERT INTO CATEGORIES (name) VALUES ('Aberturas');
INSERT INTO CATEGORIES (name) VALUES ('Construção');
INSERT INTO CATEGORIES (name) VALUES ('Encanamento');
INSERT INTO CATEGORIES (name) VALUES ('Energia');
INSERT INTO CATEGORIES (name) VALUES ('Ferramentas');
INSERT INTO CATEGORIES (name) VALUES ('Loja das Tintas');
INSERT INTO CATEGORIES (name) VALUES ('Mobiliário para Banheiros');
INSERT INTO CATEGORIES (name) VALUES ('Mobiliário para Cozinhas');
INSERT INTO CATEGORIES (name) VALUES ('Pisos e Rejuntes');
INSERT INTO CATEGORIES (name) VALUES ('Festas e Lembrancinhas');
INSERT INTO CATEGORIES (name) VALUES ('Artigos para Festas');
INSERT INTO CATEGORIES (name) VALUES ('Convites');
INSERT INTO CATEGORIES (name) VALUES ('Decoração de Festa');
INSERT INTO CATEGORIES (name) VALUES ('Descartáveis para Festa');
INSERT INTO CATEGORIES (name) VALUES ('Espuma, Serpentinas e Confete');
INSERT INTO CATEGORIES (name) VALUES ('Fantasias');
INSERT INTO CATEGORIES (name) VALUES ('Kits Imprimíveis para Festas');
INSERT INTO CATEGORIES (name) VALUES ('Lembrancinhas');
INSERT INTO CATEGORIES (name) VALUES ('Plaquinhas para Festas');
INSERT INTO CATEGORIES (name) VALUES ('Games');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios para Consoles');
INSERT INTO CATEGORIES (name) VALUES ('Consoles');
INSERT INTO CATEGORIES (name) VALUES ('Fliperamas e Arcade');
INSERT INTO CATEGORIES (name) VALUES ('Peças para Consoles');
INSERT INTO CATEGORIES (name) VALUES ('Video Games');
INSERT INTO CATEGORIES (name) VALUES ('Imóveis');
INSERT INTO CATEGORIES (name) VALUES ('Apartamentos');
INSERT INTO CATEGORIES (name) VALUES ('Casas');
INSERT INTO CATEGORIES (name) VALUES ('Chácaras');
INSERT INTO CATEGORIES (name) VALUES ('Fazendas');
INSERT INTO CATEGORIES (name) VALUES ('Flat - Apart Hotel');
INSERT INTO CATEGORIES (name) VALUES ('Galpões');
INSERT INTO CATEGORIES (name) VALUES ('Lojas Comerciais');
INSERT INTO CATEGORIES (name) VALUES ('Salas Comerciais');
INSERT INTO CATEGORIES (name) VALUES ('Sítios');
INSERT INTO CATEGORIES (name) VALUES ('Terrenos');
INSERT INTO CATEGORIES (name) VALUES ('Outros Imóveis');
INSERT INTO CATEGORIES (name) VALUES ('Indústria e Comércio');
INSERT INTO CATEGORIES (name) VALUES ('Arquitetura e Desenho');
INSERT INTO CATEGORIES (name) VALUES ('Embalagem');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento Comercial');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento de Segurança');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento para Escritórios');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento para Indústrias');
INSERT INTO CATEGORIES (name) VALUES ('Indústria Gastronômica');
INSERT INTO CATEGORIES (name) VALUES ('Indústria Gráfica e Impressão');
INSERT INTO CATEGORIES (name) VALUES ('Indústria Têxtil');
INSERT INTO CATEGORIES (name) VALUES ('Material de Promoção');
INSERT INTO CATEGORIES (name) VALUES ('Uniformes');
INSERT INTO CATEGORIES (name) VALUES ('Informática');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios de Antiestática');
INSERT INTO CATEGORIES (name) VALUES ('Armazenamento');
INSERT INTO CATEGORIES (name) VALUES ('Cabos e Hubs USB');
INSERT INTO CATEGORIES (name) VALUES ('Componentes para PC');
INSERT INTO CATEGORIES (name) VALUES ('Conectividade e Redes');
INSERT INTO CATEGORIES (name) VALUES ('Estabilizadores e No Breaks');
INSERT INTO CATEGORIES (name) VALUES ('Impressão');
INSERT INTO CATEGORIES (name) VALUES ('Leitores e Scanners');
INSERT INTO CATEGORIES (name) VALUES ('Limpeza de PCs');
INSERT INTO CATEGORIES (name) VALUES ('Monitores e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Mouses, Teclados e Controles');
INSERT INTO CATEGORIES (name) VALUES ('Palms e Handhelds');
INSERT INTO CATEGORIES (name) VALUES ('PC de Mesa');
INSERT INTO CATEGORIES (name) VALUES ('Porta CDs, Caixas e Envelopes');
INSERT INTO CATEGORIES (name) VALUES ('Portáteis e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Projetores e Telas');
INSERT INTO CATEGORIES (name) VALUES ('Software');
INSERT INTO CATEGORIES (name) VALUES ('Tablets e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Webcams e Áudio para PC');
INSERT INTO CATEGORIES (name) VALUES ('Ingressos');
INSERT INTO CATEGORIES (name) VALUES ('Eventos Esportivos');
INSERT INTO CATEGORIES (name) VALUES ('Exposições');
INSERT INTO CATEGORIES (name) VALUES ('Ingressos de Coleção');
INSERT INTO CATEGORIES (name) VALUES ('Shows');
INSERT INTO CATEGORIES (name) VALUES ('Teatro e Cultura');
INSERT INTO CATEGORIES (name) VALUES ('Outros Ingressos');
INSERT INTO CATEGORIES (name) VALUES ('Instrumentos Musicais');
INSERT INTO CATEGORIES (name) VALUES ('Baterias e Percussão');
INSERT INTO CATEGORIES (name) VALUES ('Caixas de Som');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento para DJs');
INSERT INTO CATEGORIES (name) VALUES ('Estúdio de Gravação');
INSERT INTO CATEGORIES (name) VALUES ('Instrumentos de Corda');
INSERT INTO CATEGORIES (name) VALUES ('Instrumentos de Sopro');
INSERT INTO CATEGORIES (name) VALUES ('Metrônomos');
INSERT INTO CATEGORIES (name) VALUES ('Microfones e Amplificadores');
INSERT INTO CATEGORIES (name) VALUES ('Partituras e Letras');
INSERT INTO CATEGORIES (name) VALUES ('Pedais e Acessórios');
INSERT INTO CATEGORIES (name) VALUES ('Pianos e Teclados');
INSERT INTO CATEGORIES (name) VALUES ('Joias e Relógios');
INSERT INTO CATEGORIES (name) VALUES ('Acessórios Para Relógios');
INSERT INTO CATEGORIES (name) VALUES ('Artigos de Joalharia');
INSERT INTO CATEGORIES (name) VALUES ('Canetas e Lapiseiras de Luxo');
INSERT INTO CATEGORIES (name) VALUES ('Joias e Bijuterias');
INSERT INTO CATEGORIES (name) VALUES ('Monitores e Cronômetros');
INSERT INTO CATEGORIES (name) VALUES ('Pedras Preciosas');
INSERT INTO CATEGORIES (name) VALUES ('Piercings');
INSERT INTO CATEGORIES (name) VALUES ('Porta Joias');
INSERT INTO CATEGORIES (name) VALUES ('Relógios');
INSERT INTO CATEGORIES (name) VALUES ('Smartwatches');
INSERT INTO CATEGORIES (name) VALUES ('Livros, Revistas e Comics');
INSERT INTO CATEGORIES (name) VALUES ('Catálogos');
INSERT INTO CATEGORIES (name) VALUES ('HQs');
INSERT INTO CATEGORIES (name) VALUES ('Livros');
INSERT INTO CATEGORIES (name) VALUES ('Mangá');
INSERT INTO CATEGORIES (name) VALUES ('Revistas');
INSERT INTO CATEGORIES (name) VALUES ('Música, Filmes e Seriados');
INSERT INTO CATEGORIES (name) VALUES ('Filmes');
INSERT INTO CATEGORIES (name) VALUES ('Música');
INSERT INTO CATEGORIES (name) VALUES ('Seriados');
INSERT INTO CATEGORIES (name) VALUES ('Saúde');
INSERT INTO CATEGORIES (name) VALUES ('Cuidado da Saúde');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento Médico');
INSERT INTO CATEGORIES (name) VALUES ('Massagem');
INSERT INTO CATEGORIES (name) VALUES ('Mobilidade');
INSERT INTO CATEGORIES (name) VALUES ('Ortopedia');
INSERT INTO CATEGORIES (name) VALUES ('Suplementos Alimentares');
INSERT INTO CATEGORIES (name) VALUES ('Terapias Alternativas');
INSERT INTO CATEGORIES (name) VALUES ('Serviços');
INSERT INTO CATEGORIES (name) VALUES ('Academia e Esportes');
INSERT INTO CATEGORIES (name) VALUES ('Animais');
INSERT INTO CATEGORIES (name) VALUES ('Beleza, Estética e Bem Estar');
INSERT INTO CATEGORIES (name) VALUES ('Educação');
INSERT INTO CATEGORIES (name) VALUES ('Festas e Eventos');
INSERT INTO CATEGORIES (name) VALUES ('Gastronomia');
INSERT INTO CATEGORIES (name) VALUES ('Gráficas e Impressão');
INSERT INTO CATEGORIES (name) VALUES ('Lar');
INSERT INTO CATEGORIES (name) VALUES ('Marketing e Internet');
INSERT INTO CATEGORIES (name) VALUES ('Outros Profissionais');
INSERT INTO CATEGORIES (name) VALUES ('Outros Serviços');
INSERT INTO CATEGORIES (name) VALUES ('Saúde');
INSERT INTO CATEGORIES (name) VALUES ('Suporte Técnico');
INSERT INTO CATEGORIES (name) VALUES ('Veículos e Transportes');
INSERT INTO CATEGORIES (name) VALUES ('Vestuário');
INSERT INTO CATEGORIES (name) VALUES ('Viagens e Turismo');
INSERT INTO CATEGORIES (name) VALUES ('Mais Categorias');
INSERT INTO CATEGORIES (name) VALUES ('Adultos');
INSERT INTO CATEGORIES (name) VALUES ('Birutas de vento');
INSERT INTO CATEGORIES (name) VALUES ('Coberturas Estendidas');
INSERT INTO CATEGORIES (name) VALUES ('Criptomoedas');
INSERT INTO CATEGORIES (name) VALUES ('Equipamento para Tatuagens');
INSERT INTO CATEGORIES (name) VALUES ('Esoterismo e Ocultismo');
INSERT INTO CATEGORIES (name) VALUES ('Gift Cards');
INSERT INTO CATEGORIES (name) VALUES ('Kits de Criminologia');
INSERT INTO CATEGORIES (name) VALUES ('Licenças para Taxis');
INSERT INTO CATEGORIES (name) VALUES ('Tabacaria');
INSERT INTO CATEGORIES (name) VALUES ('Outros');